-- ============================================================================
-- Auto-generated post plans with an approval gate
-- ============================================================================
-- Nothing generated by the app may publish on its own. A planned post is
-- created as 'needs_approval'; only a human moving it to 'pending' puts it in
-- front of the scheduler, which has always picked up 'pending' and nothing
-- else. That means the publishing path itself is unchanged — the gate sits in
-- front of it rather than inside it.
--
-- Statuses now in use:
--   needs_approval → waiting on a person
--   pending        → approved, scheduler will publish at scheduled_at
--   publishing     → claimed by the scheduler
--   published      → done
--   failed         → the API rejected it
--   missed         → its time came and went without approval
-- ============================================================================

-- 1. Approval and provenance columns -----------------------------------------
ALTER TABLE public.scheduled_posts
  ADD COLUMN IF NOT EXISTS approved_by    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS approved_at    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS plan_id        UUID,
  ADD COLUMN IF NOT EXISTS assigned_to    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS feature_ids    UUID[],
  ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.scheduled_posts.auto_generated IS
  'True for posts the planner created. These must be approved before they can
   reach ''pending''; posts composed by hand are already a deliberate act.';

CREATE INDEX IF NOT EXISTS scheduled_posts_status_time_idx
  ON public.scheduled_posts (status, scheduled_at);

CREATE INDEX IF NOT EXISTS scheduled_posts_plan_idx
  ON public.scheduled_posts (plan_id) WHERE plan_id IS NOT NULL;

-- 2. The plan a batch of posts came from --------------------------------------
CREATE TABLE IF NOT EXISTS public.post_plans (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id    TEXT NOT NULL,
  period      DATE NOT NULL,
  cadence     TEXT NOT NULL,              -- '1x' | '2x' | '3x' | 'custom'
  per_week    INT  NOT NULL DEFAULT 1,
  grouping    TEXT NOT NULL DEFAULT 'product',   -- 'product' | 'category'
  publish_to  TEXT[] NOT NULL DEFAULT '{facebook}',
  time_source TEXT NOT NULL DEFAULT 'manual',    -- 'meta' | 'manual'
  notes       TEXT,
  created_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS post_plans_store_period_idx
  ON public.post_plans (store_id, period DESC);

-- 3. Who may see and approve --------------------------------------------------
-- The original policies scoped everything to the row's creator, which breaks
-- the moment approval is someone else's job: a store manager could not see a
-- post the planner created under an admin's account. Store membership is the
-- right unit now.
DROP POLICY IF EXISTS "sp_select" ON public.scheduled_posts;
CREATE POLICY "sp_select" ON public.scheduled_posts FOR SELECT USING (
  created_by = auth.uid()
  OR public.is_admin()
  OR store_id = ANY (public.my_store_ids())
);

DROP POLICY IF EXISTS "sp_update" ON public.scheduled_posts;
CREATE POLICY "sp_update" ON public.scheduled_posts FOR UPDATE USING (
  created_by = auth.uid()
  OR public.is_admin()
  OR store_id = ANY (public.my_store_ids())
);

DROP POLICY IF EXISTS "sp_delete" ON public.scheduled_posts;
CREATE POLICY "sp_delete" ON public.scheduled_posts FOR DELETE USING (
  created_by = auth.uid()
  OR public.is_admin()
  OR store_id = ANY (public.my_store_ids())
);

ALTER TABLE public.post_plans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS post_plans_read  ON public.post_plans;
DROP POLICY IF EXISTS post_plans_write ON public.post_plans;

CREATE POLICY post_plans_read ON public.post_plans
  FOR SELECT TO authenticated USING (true);

CREATE POLICY post_plans_write ON public.post_plans
  FOR ALL TO authenticated
  USING      (public.is_admin() OR store_id = ANY (public.my_store_ids()))
  WITH CHECK (public.is_admin() OR store_id = ANY (public.my_store_ids()));

-- 4. The gate itself ----------------------------------------------------------
-- Enforced in the database, not the browser. RLS lets a store member update
-- their store's rows, and without this they could simply PATCH status to
-- 'pending' and skip the review. The trigger is also what stamps who approved
-- and when, so those two columns can't be back-dated or attributed to someone
-- else by whoever sent the request.
CREATE OR REPLACE FUNCTION public.enforce_post_approval()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- The scheduler runs as the service role and must stay unencumbered: it
  -- moves rows pending → publishing → published without approving anything.
  IF current_setting('request.jwt.claims', true) IS NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.auto_generated
     AND NEW.status = 'pending'
     AND OLD.status = 'needs_approval' THEN
    NEW.approved_by := auth.uid();
    NEW.approved_at := now();
  END IF;

  IF NEW.auto_generated
     AND NEW.status = 'pending'
     AND NEW.approved_at IS NULL THEN
    RAISE EXCEPTION 'This post has to be approved before it can be scheduled';
  END IF;

  -- Editing an approved post sends it back for review. Approving a caption and
  -- then quietly rewriting it would make the sign-off meaningless.
  IF NEW.auto_generated
     AND OLD.status = 'pending'
     AND NEW.status = 'pending'
     AND (NEW.caption IS DISTINCT FROM OLD.caption
          OR NEW.image_url IS DISTINCT FROM OLD.image_url
          OR NEW.image_urls IS DISTINCT FROM OLD.image_urls) THEN
    NEW.status      := 'needs_approval';
    NEW.approved_by := NULL;
    NEW.approved_at := NULL;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS scheduled_posts_approval ON public.scheduled_posts;
CREATE TRIGGER scheduled_posts_approval
  BEFORE UPDATE ON public.scheduled_posts
  FOR EACH ROW EXECUTE FUNCTION public.enforce_post_approval();

-- An insert can't arrive pre-approved either.
CREATE OR REPLACE FUNCTION public.enforce_post_approval_insert()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF current_setting('request.jwt.claims', true) IS NULL THEN
    RETURN NEW;
  END IF;
  IF NEW.auto_generated AND NEW.status <> 'needs_approval' THEN
    NEW.status := 'needs_approval';
    NEW.approved_by := NULL;
    NEW.approved_at := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS scheduled_posts_approval_insert ON public.scheduled_posts;
CREATE TRIGGER scheduled_posts_approval_insert
  BEFORE INSERT ON public.scheduled_posts
  FOR EACH ROW EXECUTE FUNCTION public.enforce_post_approval_insert();

-- 5. Verify -------------------------------------------------------------------
-- SELECT status, count(*) FROM public.scheduled_posts GROUP BY status;

NOTIFY pgrst, 'reload schema';
