-- ============================================================================
-- Cocktail recipe library
-- ============================================================================
-- A recipe is written once and reused: the same Bacardi mojito card serves
-- every summer it goes on feature. So recipes are stored, not generated on the
-- way past, and they keep a link back to the product and the feature that
-- prompted them.
--
-- Card artwork is composed on canvas from the product shot, not generated by an
-- image model — the look has to stay consistent across a set, and a photo model
-- gives a different drink every time you press the button.
-- ============================================================================

-- 1. Recipes ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.recipes (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         TEXT NOT NULL,
  -- NULL means it belongs to the whole chain. A recipe built around a product
  -- only one store carries can be scoped to that store.
  store_id     TEXT,
  product_id   UUID REFERENCES public.brand_images(id) ON DELETE SET NULL,
  feature_id   UUID REFERENCES public.features(id)     ON DELETE SET NULL,

  glass        TEXT,
  -- [{ "amount": "2 oz", "item": "white rum" }, ...] — kept as an array rather
  -- than a blob of text so the caption and the card can lay it out differently.
  ingredients  JSONB NOT NULL DEFAULT '[]'::jsonb,
  method       TEXT[] NOT NULL DEFAULT '{}',
  garnish      TEXT,
  notes        TEXT,

  -- The rendered card, once one has been built.
  image_url    TEXT,
  creative_id  UUID REFERENCES public.creatives(id) ON DELETE SET NULL,

  created_by   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS recipes_store_idx   ON public.recipes (store_id);
CREATE INDEX IF NOT EXISTS recipes_product_idx ON public.recipes (product_id);
CREATE INDEX IF NOT EXISTS recipes_name_idx    ON public.recipes (lower(name));

DROP TRIGGER IF EXISTS recipes_touch ON public.recipes;
CREATE TRIGGER recipes_touch
  BEFORE UPDATE ON public.recipes
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- 2. Card styling -------------------------------------------------------------
-- One row per store, plus a chain-wide default (store_id NULL). Held as JSONB
-- because this is a look, not a schema: adding a corner treatment shouldn't
-- cost a migration, and unknown keys are merged over defaults in the app.
CREATE TABLE IF NOT EXISTS public.recipe_styles (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id   TEXT UNIQUE,
  tokens     JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ
);

-- One NULL store_id only — Postgres treats NULLs as distinct in a UNIQUE
-- constraint, so the chain-wide row needs its own guard.
CREATE UNIQUE INDEX IF NOT EXISTS recipe_styles_default_unique
  ON public.recipe_styles ((1)) WHERE store_id IS NULL;

DROP TRIGGER IF EXISTS recipe_styles_touch ON public.recipe_styles;
CREATE TRIGGER recipe_styles_touch
  BEFORE UPDATE ON public.recipe_styles
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- 3. 4:5 is a real size now ---------------------------------------------------
-- 1080×1350 is Instagram's tallest feed size and the one recipe cards want.
-- The creatives table only allowed the four sizes that existed when it was
-- written.
ALTER TABLE public.creatives DROP CONSTRAINT IF EXISTS creatives_aspect_check;
ALTER TABLE public.creatives
  ADD CONSTRAINT creatives_aspect_check
  CHECK (aspect IN ('1:1','4:5','3:5','16:9','1.91:1'));

-- 4. RLS ----------------------------------------------------------------------
ALTER TABLE public.recipes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_styles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS recipes_read  ON public.recipes;
DROP POLICY IF EXISTS recipes_write ON public.recipes;

-- Recipes are shared knowledge — every store can read every recipe.
CREATE POLICY recipes_read ON public.recipes
  FOR SELECT TO authenticated USING (true);

CREATE POLICY recipes_write ON public.recipes
  FOR ALL TO authenticated
  USING      (public.is_admin() OR store_id IS NULL OR store_id = ANY (public.my_store_ids()))
  WITH CHECK (public.is_admin() OR store_id IS NULL OR store_id = ANY (public.my_store_ids()));

DROP POLICY IF EXISTS recipe_styles_read  ON public.recipe_styles;
DROP POLICY IF EXISTS recipe_styles_write ON public.recipe_styles;

CREATE POLICY recipe_styles_read ON public.recipe_styles
  FOR SELECT TO authenticated USING (true);

-- The chain-wide look is an admin decision; a store may set its own.
CREATE POLICY recipe_styles_write ON public.recipe_styles
  FOR ALL TO authenticated
  USING      (public.is_admin() OR (store_id IS NOT NULL AND store_id = ANY (public.my_store_ids())))
  WITH CHECK (public.is_admin() OR (store_id IS NOT NULL AND store_id = ANY (public.my_store_ids())));

-- 5. Verify -------------------------------------------------------------------
-- SELECT count(*) FROM public.recipes;
-- SELECT store_id, tokens FROM public.recipe_styles;

NOTIFY pgrst, 'reload schema';
